/**
 * bin_packing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CargoRequest } from '../model/models';
import { CargoResponse } from '../model/models';
import { Item } from '../model/models';
import { ProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BinPackingServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param cargoRequest 
     */
    calculateCargo(cargoRequest: CargoRequest, extraHttpRequestParams?: any): Observable<CargoResponse>;

    /**
     * 
     * 
     * @param delimiter 
     */
    uploadCargoFile(delimiter: string, extraHttpRequestParams?: any): Observable<Array<Item>>;

}
