/**
 * bin_packing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Vehicle } from './vehicle';
import { Item } from './item';


export interface CargoRequest { 
    id?: string | null;
    cargoItems?: Array<Item> | null;
    vehicle?: Vehicle;
}

