/**
 * bin_packing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ItemWithPositions { 
    id?: number;
    w: number;
    l: number;
    h: number;
    quantity?: number;
    weight?: number;
    stackable?: boolean;
    uprightOnly?: boolean;
    itemMaxStackWeight?: number | null;
    positionX: number;
    positionY: number;
    positionZ: number;
}

