/**
 * bin_packing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Axel } from './axel';


export interface Vehicle { 
    w?: number;
    l?: number;
    h?: number;
    maxWeight?: number;
    axles?: Array<Axel> | null;
}

