/**
 * bin_packing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Axel } from './axel';
import { CenterOfMass } from './centerOfMass';


export interface Vehicle { 
    width?: number;
    length?: number;
    height?: number;
    maxWeight?: number;
    axles?: Array<Axel> | null;
    centerOfMass?: CenterOfMass;
    currentWeight?: number;
    currentVolume?: number;
}

